import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // next-env.d.ts is auto-generated by Next.js itself (regenerated on every
  // dev/build run) and .next/ is build output — `next build`'s own lint
  // step already skips both, but a bare `eslint .` (pnpm lint, CI) doesn't
  // unless told to.
  { ignores: [".next/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
